# Generated by Django 4.1.6 on 2023-02-11 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_no', models.CharField(blank=True, default=0, max_length=12)),
                ('pan_no', models.CharField(blank=True, default=0, max_length=10)),
                ('type_of_employment', models.CharField(blank=True, choices=[('Self_employed', 'Self_employed'), ('Private', 'Private')], default=0, max_length=250)),
                ('business_title', models.CharField(blank=True, default=0, max_length=250)),
                ('business_type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Partnership', 'Partnership'), ('Corporation', 'Corporation'), ('Propriership', 'Propritorship')], default=0, max_length=250)),
                ('business_address', models.TextField(blank=True, default=0)),
                ('gst_registration_no', models.CharField(blank=True, default=0, max_length=50)),
                ('business_license_no', models.CharField(blank=True, default=0, max_length=50)),
                ('expected_average_annual_turnover', models.CharField(blank=True, default=0, max_length=250)),
                ('years_in_current_business', models.IntegerField(blank=True, default=0)),
                ('collateral', models.CharField(blank=True, default=0, max_length=250)),
                ('status', models.CharField(choices=[('Inprocess', 'Inprocess'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='', max_length=250)),
                ('application_timestamp', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, default=0, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_with_customer', models.CharField(blank=True, default=0, max_length=250)),
                ('name', models.CharField(blank=True, default=0, max_length=150)),
                ('dob', models.DateField(blank=True, default='2000-12-12')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=0, max_length=50)),
                ('email', models.EmailField(blank=True, default=0, max_length=254)),
                ('address', models.TextField(blank=True, default=0, max_length=250)),
                ('city', models.CharField(blank=True, default=0, max_length=50)),
                ('state', models.CharField(blank=True, default=0, max_length=50)),
                ('country', models.CharField(blank=True, default=0, max_length=250)),
                ('pin_code', models.IntegerField(blank=True, default=0)),
                ('mobile', models.CharField(blank=True, default=0, max_length=10)),
                ('photo', models.ImageField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('profession', models.CharField(blank=True, default=0, max_length=250)),
                ('income_certificate', models.FileField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('bank_name', models.CharField(blank=True, default=0, max_length=250)),
                ('current_account_no', models.CharField(blank=True, default=0, max_length=20)),
                ('passbook_copy', models.FileField(blank=True, default=0, upload_to='media/customer/guarantor/')),
                ('ifsc_code', models.CharField(blank=True, default=0, max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Guarantors', to='application_generation.application')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, default=0, max_length=250)),
                ('father_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('mother_name', models.CharField(blank=True, default=0, max_length=250)),
                ('mother_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorse', 'Divorse')], default=0, max_length=250)),
                ('spouse_name', models.CharField(blank=True, default=0, max_length=250)),
                ('spouse_profession', models.CharField(blank=True, default=0, max_length=250)),
                ('mobile', models.CharField(blank=True, default=0, max_length=10)),
                ('address', models.TextField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Familys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_title', models.CharField(blank=True, default=0, max_length=250)),
                ('email', models.EmailField(blank=True, default=0, max_length=254)),
                ('contact_details_1', models.CharField(max_length=15)),
                ('contact_details_2', models.CharField(max_length=15)),
                ('udyog_aadhar_no', models.CharField(blank=True, default=0, max_length=50)),
                ('gst_registration_no', models.CharField(blank=True, default=0, max_length=50)),
                ('business_license_no', models.CharField(blank=True, default=0, max_length=50)),
                ('pan_card_no', models.CharField(blank=True, default=0, max_length=50)),
                ('date_of_incorporation', models.DateField(blank=True)),
                ('business_type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Partnership', 'Partnership'), ('Corporation', 'Corporation'), ('Propriership', 'Propritorship')], default=0, max_length=250)),
                ('business_constitution', models.CharField(blank=True, choices=[('Private_limited', 'Private_limited'), ('Public_limited', 'Public_limited'), ('Partnership', 'Partnership'), ('One_person_companies', 'One_person_companies')], default='owner', max_length=100)),
                ('business_address', models.TextField(blank=True, default=0)),
                ('CIBIL_score', models.IntegerField(blank=True, default=0)),
                ('past1_year_turnover', models.CharField(blank=True, default=0, max_length=50)),
                ('past2_year_turnover', models.CharField(blank=True, default=0, max_length=50)),
                ('expected_average_annual_turnover', models.CharField(blank=True, default=0, max_length=250)),
                ('years_in_current_business', models.IntegerField(blank=True, default=0)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Business', to='application_generation.application')),
            ],
        ),
    ]
